import { useMemo, useState, type ReactNode } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { toast } from "sonner";
import { Activity, ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Filter, LayoutDashboard, ListTodo, LogIn, LogOut, MoreHorizontal, Plus, Search, Settings2, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { SupabaseAuthGate } from "@/components/supabase-auth-gate";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useTasks, type Task } from "@/hooks/use-tasks";
import { supabase } from "@/lib/supabase";

export const Route = createFileRoute("/")({
  component: Index,
  head: () => ({ meta: [
    { title: "TaskFlow — Team operations, in sync" },
    { name: "description", content: "A focused workspace for managing multi-tenant teams, tasks, and delivery." },
    { property: "og:title", content: "TaskFlow — Team operations, in sync" },
    { property: "og:description", content: "A focused workspace for managing multi-tenant teams, tasks, and delivery." },
  ] }),
});

function TaskFlowMark({ className }: { className?: string }) {
  return <img src="/taskflow-icon.svg" alt="" className={className} />;
}

function Index() {
  return <SupabaseAuthGate>{(session, openSignIn) => <Dashboard key={session?.user.id ?? "guest"} userId={session?.user.id ?? null} onSignIn={openSignIn} />}</SupabaseAuthGate>;
}

function Dashboard({ userId, onSignIn }: { userId: string | null; onSignIn: () => void }) {
  const [activeView, setActiveView] = useState<"overview" | "tasks">("overview");
  const [taskFilter, setTaskFilter] = useState<"all" | "my" | "priority">("all");
  const [query, setQuery] = useState("");
  const [showNewTask, setShowNewTask] = useState(false);
  const [newTask, setNewTask] = useState("");
  const { tasks, tasksLoading, toggleTask, createTask } = useTasks(userId);
  const visibleTasks = useMemo(() => {
    const q = query.trim().toLowerCase();
    return tasks.filter((task) => {
      const matchesQuery = !q || `${task.title} ${task.project} ${task.owner}`.toLowerCase().includes(q);
      const matchesFilter = taskFilter === "all" || (taskFilter === "my" && task.owner === "You") || (taskFilter === "priority" && task.priority === "High");
      return matchesQuery && matchesFilter;
    });
  }, [query, taskFilter, tasks]);
  const completedCount = tasks.filter((task) => task.status === "Done").length;
  async function addTask() { if (!newTask.trim()) return; const task = await createTask(newTask.trim()); if (!task) return; setNewTask(""); setShowNewTask(false); }

  return <div className="min-h-screen bg-background text-foreground"><div className="flex min-h-screen">
    <aside className="hidden w-[248px] shrink-0 flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground lg:flex">
      <div className="flex h-[76px] items-center gap-3 border-b border-sidebar-border px-6"><div className="flex size-9 items-center justify-center rounded-md bg-brand text-brand-foreground"><TaskFlowMark className="size-5" /></div><div><div className="font-display text-lg font-bold tracking-tight">taskflow</div><div className="text-[10px] uppercase tracking-[0.18em] text-sidebar-foreground/55">workspace OS</div></div></div>
      <div className="px-4 py-5"><button className="flex w-full items-center justify-between rounded-md bg-sidebar-hover px-3 py-2.5 text-left text-sm transition-colors hover:bg-sidebar-hover/80" onClick={() => toast("Northstar workspace selected")}><span className="flex items-center gap-2.5"><span className="flex size-7 items-center justify-center rounded bg-brand/15 text-xs font-bold text-brand">N</span><span><span className="block font-semibold text-sidebar-foreground">Northstar Labs</span><span className="block text-xs text-sidebar-foreground/55">Acme organization</span></span></span><ChevronDown className="size-4 text-sidebar-foreground/50" /></button></div>
      <nav className="space-y-1 px-4" aria-label="Main navigation"><NavItem icon={<LayoutDashboard />} label="Overview" active={activeView === "overview"} onClick={() => setActiveView("overview")} /><NavItem icon={<ListTodo />} label="My tasks" active={activeView === "tasks"} onClick={() => setActiveView("tasks")} count={tasks.filter((task) => task.owner === "You" && task.status !== "Done").length} /><NavItem icon={<CalendarDays />} label="Timeline" onClick={() => toast("Timeline view is coming next")} /><NavItem icon={<Users />} label="People" onClick={() => toast("People directory opened")} /></nav>
      <div className="mt-8 px-6 text-[10px] font-bold uppercase tracking-[0.18em] text-sidebar-foreground/40">Workspace</div><nav className="mt-2 space-y-1 px-4"><NavItem icon={<Activity />} label="Activity" onClick={() => toast("Activity feed opened")} /><NavItem icon={<ShieldCheck />} label="Security & roles" onClick={() => toast("Security controls opened")} /><NavItem icon={<Settings2 />} label="Settings" onClick={() => toast("Workspace settings opened")} /></nav>
      <div className="mt-auto p-4"><div className="rounded-md border border-sidebar-border bg-sidebar-hover/50 p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold">Storage</span><span className="text-xs text-sidebar-foreground/55">62%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-sidebar-border"><div className="h-full w-[62%] rounded-full bg-brand" /></div><p className="mt-2 text-[11px] leading-relaxed text-sidebar-foreground/50">Your workspace is running smoothly.</p></div><div className="mt-4 flex items-center gap-3 border-t border-sidebar-border pt-4"><Avatar className="size-8"><AvatarFallback className="bg-brand text-xs font-bold text-brand-foreground">JD</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">Jordan Davis</div><div className="text-xs text-sidebar-foreground/50">{userId ? "Admin" : "Guest"}</div></div>{userId ? <button aria-label="Sign out" title="Sign out" className="text-sidebar-foreground/50 hover:text-sidebar-foreground" onClick={() => void supabase?.auth.signOut()}><LogOut className="size-4" /></button> : <button aria-label="Sign in" title="Sign in" className="text-sidebar-foreground/50 hover:text-sidebar-foreground" onClick={onSignIn}><LogIn className="size-4" /></button>}</div></div>
    </aside>
    <main className="min-w-0 flex-1"><header className="flex h-[76px] items-center justify-between border-b border-border bg-surface-raised px-5 backdrop-blur-md sm:px-8"><div className="flex items-center gap-3 lg:hidden"><div className="flex size-8 items-center justify-center rounded-md bg-primary text-primary-foreground"><TaskFlowMark className="size-4" /></div><span className="font-display font-bold">taskflow</span></div><div className="relative hidden w-full max-w-[360px] sm:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tasks, people, projects" className="h-10 border-border bg-background pl-9 pr-12 text-sm shadow-none" /><kbd className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-[10px] text-muted-foreground">⌘ K</kbd></div><div className="ml-auto flex items-center gap-2"><Button variant="outline" size="sm" className="gap-2" onClick={userId ? () => void supabase?.auth.signOut() : onSignIn}>{userId ? <LogOut className="size-4" /> : <LogIn className="size-4" />}{userId ? "Sign out" : "Sign in"}</Button><Button variant="ghost" size="icon" aria-label="Help" onClick={() => toast("How can we help?")}><CircleHelp className="size-[18px]" /></Button><Button variant="ghost" size="icon" aria-label="Notifications" onClick={() => toast("You are all caught up")}><Bell className="size-[18px]" /><span className="absolute ml-3 mt-[-13px] size-1.5 rounded-full bg-brand" /></Button><div className="mx-2 hidden h-6 w-px bg-border sm:block" /><Avatar className="size-8 sm:hidden"><AvatarFallback className="bg-primary text-xs text-primary-foreground">JD</AvatarFallback></Avatar><Button onClick={() => setShowNewTask(true)} className="h-9 gap-2 bg-primary px-3 text-xs font-semibold text-primary-foreground shadow-sm hover:bg-primary/90"><Plus className="size-4" /> New task</Button></div></header>
      <div className="mx-auto max-w-[1440px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9"><div className="taskflow-rise mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-muted-foreground">Tuesday, September 29, 2026</p><h1 className="text-[2rem] font-bold tracking-[-0.04em] sm:text-[2.65rem]">Good morning, Jordan <span className="text-brand">↗</span></h1><p className="mt-2 text-sm text-muted-foreground">Here’s the pulse of Northstar Labs today.</p></div><div className="flex items-center gap-2"><Button variant={activeView === "overview" ? "secondary" : "ghost"} className="h-9 text-xs" onClick={() => setActiveView("overview")}>Overview</Button><Button variant={activeView === "tasks" ? "secondary" : "ghost"} className="h-9 text-xs" onClick={() => setActiveView("tasks")}>My tasks <span className="ml-1 rounded bg-background px-1.5 py-0.5 text-[10px]">{tasks.filter((task) => task.owner === "You" && task.status !== "Done").length}</span></Button></div></div>
        <section className="taskflow-rise taskflow-delay-1 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={<ListTodo />} label="Total tasks" value={String(tasks.length + 18)} detail="Across all projects" tone="blue" /><MetricCard icon={<Check />} label="Completed" value={String(completedCount + 42)} detail="71% completion rate" tone="green" trend="+12%" /><MetricCard icon={<Clock3 />} label="In progress" value={String(tasks.filter((task) => task.status === "In progress").length + 8)} detail="Across 4 projects" tone="amber" /><MetricCard icon={<Sparkles />} label="Team velocity" value="84%" detail="↑ 8% from last week" tone="violet" trend="Healthy" /></section>
        <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,0.75fr)]"><section className="taskflow-rise taskflow-delay-2 min-w-0 rounded-md border border-border bg-card shadow-[0_12px_32px_-24px_oklch(0.3_0.04_255/0.5)]"><div className="flex flex-col gap-4 border-b border-border px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold tracking-tight">Task overview</h2><p className="mt-1 text-xs text-muted-foreground">The latest work across your workspace.</p></div><Button variant="outline" className="h-9 w-fit gap-2 text-xs" onClick={() => setShowNewTask(true)}><Plus className="size-3.5" /> Add task</Button></div><div className="flex flex-wrap items-center gap-1 border-b border-border px-5 py-3"><Filter className="mr-2 size-3.5 text-muted-foreground" /><FilterButton active={taskFilter === "all"} onClick={() => setTaskFilter("all")}>All tasks</FilterButton><FilterButton active={taskFilter === "my"} onClick={() => setTaskFilter("my")}>Assigned to me</FilterButton><FilterButton active={taskFilter === "priority"} onClick={() => setTaskFilter("priority")}>High priority</FilterButton></div><div className="divide-y divide-border">{tasksLoading ? <div className="px-5 py-12 text-center text-sm text-muted-foreground">Loading tasks...</div> : visibleTasks.slice(0, activeView === "tasks" ? 8 : 5).map((task) => <TaskRow key={task.id} task={task} onToggle={() => toggleTask(task.id)} />)}{!tasksLoading && visibleTasks.length === 0 && <div className="px-5 py-12 text-center text-sm text-muted-foreground">No tasks match your filters.</div>}</div><div className="flex items-center justify-between border-t border-border px-5 py-4"><span className="text-xs text-muted-foreground">Showing {Math.min(visibleTasks.length, activeView === "tasks" ? 8 : 5)} of {visibleTasks.length} tasks</span><Button variant="ghost" className="h-8 gap-1 px-2 text-xs text-primary" onClick={() => setActiveView("tasks")}>View all <ArrowUpRight className="size-3.5" /></Button></div></section>
          <aside className="taskflow-rise taskflow-delay-3 space-y-6"><section className="rounded-md border border-border bg-card px-5 py-5 shadow-[0_12px_32px_-24px_oklch(0.3_0.04_255/0.5)]"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-bold tracking-tight">Project progress</h2><p className="mt-1 text-xs text-muted-foreground">This week’s delivery health.</p></div><button aria-label="Project options" className="text-muted-foreground hover:text-foreground" onClick={() => toast("Project options opened")}><MoreHorizontal className="size-4" /></button></div><div className="space-y-5"><ProgressItem label="Website redesign" meta="12 / 18 tasks" value={67} color="bg-chart-1" /><ProgressItem label="Mobile app v2" meta="8 / 12 tasks" value={66} color="bg-chart-2" /><ProgressItem label="Q4 launch plan" meta="5 / 9 tasks" value={55} color="bg-chart-3" /></div><Button variant="outline" className="mt-5 h-9 w-full text-xs" onClick={() => toast("Projects view opened")}>View projects <ArrowUpRight className="size-3.5" /></Button></section><section className="rounded-md border border-border bg-primary px-5 py-5 text-primary-foreground"><div className="mb-4 flex items-center justify-between"><div className="flex size-9 items-center justify-center rounded bg-brand text-brand-foreground"><Sparkles className="size-4" /></div><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-primary-foreground/50">Insight</span></div><h3 className="font-display text-xl font-bold leading-tight">Your team is moving fast.</h3><p className="mt-2 text-xs leading-relaxed text-primary-foreground/65">Completion is up 12% this week. Keep the momentum by clearing the 3 blocked tasks.</p><Button variant="secondary" className="mt-5 h-9 w-full text-xs" onClick={() => toast("Blocked tasks filtered")}>Review blocked tasks <ArrowUpRight className="size-3.5" /></Button></section></aside></div>
      </div></main>
    </div>{showNewTask && <div className="fixed inset-0 z-50 flex items-center justify-center bg-primary/25 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Create a new task"><div className="w-full max-w-[460px] rounded-md border border-border bg-card p-6 shadow-2xl"><div className="mb-6 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-foreground/60">Quick capture</p><h2 className="mt-1 font-display text-2xl font-bold">Create a task</h2></div><Button variant="ghost" size="icon" aria-label="Close" onClick={() => setShowNewTask(false)}><X className="size-4" /></Button></div><label className="text-xs font-semibold text-muted-foreground" htmlFor="task-title">What needs to happen?</label><Input autoFocus id="task-title" value={newTask} onChange={(event) => setNewTask(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") addTask(); }} placeholder="e.g. Review launch checklist" className="mt-2 h-11 bg-background" /><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={() => setShowNewTask(false)}>Cancel</Button><Button onClick={addTask} disabled={!newTask.trim()}><Plus className="size-4" /> Create task</Button></div></div></div>}</div>;
}

function NavItem({ icon, label, active, count, onClick }: { icon: ReactNode; label: string; active?: boolean; count?: number; onClick: () => void }) { return <button onClick={onClick} className={`flex h-10 w-full items-center gap-3 rounded-md px-3 text-sm transition-colors ${active ? "bg-sidebar-primary text-sidebar-primary-foreground" : "text-sidebar-foreground/65 hover:bg-sidebar-hover hover:text-sidebar-foreground"}`}><span className="[&>svg]:size-[17px]">{icon}</span><span className="flex-1 text-left">{label}</span>{count !== undefined && <span className={`rounded px-1.5 py-0.5 text-[10px] font-bold ${active ? "bg-sidebar-primary-foreground/15" : "bg-sidebar-hover"}`}>{count}</span>}</button>; }
function MetricCard({ icon, label, value, detail, tone, trend }: { icon: ReactNode; label: string; value: string; detail: string; tone: "blue" | "green" | "amber" | "violet"; trend?: string }) { const tones = { blue: "bg-brand-soft text-brand-foreground", green: "bg-success-soft text-success", amber: "bg-warning-soft text-warning", violet: "bg-accent text-accent-foreground" }; return <div className="rounded-md border border-border bg-card p-4 shadow-[0_8px_24px_-22px_oklch(0.3_0.04_255/0.55)]"><div className="mb-4 flex items-start justify-between"><span className={`flex size-8 items-center justify-center rounded ${tones[tone]}`}><span className="[&>svg]:size-4">{icon}</span></span>{trend && <span className="rounded bg-success-soft px-2 py-1 text-[10px] font-bold text-success">{trend}</span>}</div><div className="font-display text-2xl font-bold tracking-tight">{value}</div><div className="mt-1 text-xs font-medium text-muted-foreground">{label} <span className="mx-1 text-border">·</span> {detail}</div></div>; }
function FilterButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button onClick={onClick} className={`rounded px-2.5 py-1.5 text-xs font-semibold transition-colors ${active ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{children}</button>; }
function TaskRow({ task, onToggle }: { task: Task; onToggle: () => void }) { const priorityTone = { High: "bg-danger-soft text-danger", Medium: "bg-warning-soft text-warning", Low: "bg-muted text-muted-foreground" }[task.priority]; return <div className="group flex items-center gap-3 px-5 py-4 transition-colors hover:bg-muted/40"><button aria-label={`Mark ${task.title} ${task.status === "Done" ? "incomplete" : "complete"}`} onClick={onToggle} className={`flex size-[18px] shrink-0 items-center justify-center rounded-full border transition-colors ${task.status === "Done" ? "border-success bg-success text-primary-foreground" : "border-border bg-background hover:border-brand"}`}>{task.status === "Done" && <Check className="size-3" />}</button><div className="min-w-0 flex-1"><div className={`truncate text-sm font-semibold ${task.status === "Done" ? "text-muted-foreground line-through" : "text-foreground"}`}>{task.title}</div><div className="mt-1 flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground"><span>{task.project}</span><span className="text-border">·</span><span>{task.owner}</span></div></div><Badge variant="outline" className={`${priorityTone} hidden border-0 px-2 py-1 text-[10px] sm:inline-flex`}>{task.priority}</Badge><span className={`hidden items-center gap-1 text-[11px] font-medium md:flex ${task.due === "Today" ? "text-danger" : "text-muted-foreground"}`}><CalendarDays className="size-3" />{task.due}</span><button aria-label={`More options for ${task.title}`} onClick={() => toast("Task options opened")} className="ml-1 text-muted-foreground opacity-0 transition-opacity hover:text-foreground group-hover:opacity-100"><MoreHorizontal className="size-4" /></button></div>; }
function ProgressItem({ label, meta, value, color }: { label: string; meta: string; value: number; color: string }) { return <div><div className="mb-2 flex items-center justify-between text-xs"><span className="font-semibold">{label}</span><span className="text-muted-foreground">{meta}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div></div>; }